export const theme = {
  colors: {
    primary20: '#E5F0FC',
    primary60: '#92D1FF',
    primary80: '#F2C94C',
    primary100: '#F2994A',
    red: '#ff0000',
    orange: '#FC7E2F',
    green: '#28B62A',
    purple: '#7000FF',
    pink: '#EE107A',
    yellow: '#FFE976',
    navy: '#1262D6',
    lightRed: '#FFF3F3',
    lightOrange: '#FFF4ED',
    lightGreen: '#E4F2E4',
    lightPurple: '#EBE0FA',
    lightPink: '#F8E2EC',
    lightBlue: '#EFF6FC',
    neutral0: '#FFF',
    neutral10: '#F9FAFB',
    neutral20: '#F3F5F8',
    neutral25: '#EDEEF0',
    neutral30: '#E8EAEE',
    neutral40: '#D1D6DB',
    neutral45: '#B0B0B0',
    neutral50: '#A3AAB6',
    neutral60: '#6B7684',
    neutral70: '#6D727A',
    neutral100: '#1E1E1E',
  },
  families: {
    extraBold: 'Pretendard-ExtraBold',
    extraLight: 'Pretendard-ExtraLight',
    semiBold: 'Pretendard-SemiBold',
    regular: 'Pretendard-Regular',
    medium: 'Pretendard-Medium',
    light: 'Pretendard-Light',
    black: 'Pretendard-Black',
    bold: 'Pretendard-Bold',
    thin: 'Pretendard-Thin',
  },
};
